# Generated by Django 5.2.6 on 2025-10-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada')], default='livre', max_length=10)),
            ],
        ),
    ]
