# Generated by Django 5.2.6 on 2025-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
