# Generated by Django 5.2.6 on 2025-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0002_alter_vaga_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_maximo', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
