# Generated by Django 5.2.6 on 2025-11-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0003_configuracaovaga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoVaga',
        ),
    ]
