# Generated by Django 5.2.6 on 2025-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0004_delete_configuracaovaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
