version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      # SQLite usa arquivo local, então mantemos o volume para persistência
    command: python manage.py runserver 0.0.0.0:8000

