# Generated by Django 5.2.6 on 2025-09-17 17:18

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(default='F', editable=False, max_length=1)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='funcionarios_fotos/', variations={'medium': {'crop': True, 'height': 300, 'width': 300}, 'thumbnail': {'crop': True, 'height': 100, 'width': 100}})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
