# Generated by Django 5.2.6 on 2025-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_remove_funcionario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf_func',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
