# Generated by Django 5.2.6 on 2025-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_cpf_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_func',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Funcionário'),
        ),
    ]
