# Generated by Django 5.2.6 on 2025-09-24 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('veiculo', '0002_veiculo_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('numero_vaga', models.CharField(max_length=10)),
                ('status_vaga', models.BooleanField(default=True)),
                ('valor_pagamento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('modalidade_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('pix', 'Pix')], max_length=10, null=True)),
                ('tempo_total', models.DurationField(blank=True, null=True)),
                ('funcionario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadas', to='veiculo.veiculo')),
            ],
        ),
    ]
