# Generated by Django 5.2.6 on 2025-10-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estada', '0001_initial'),
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estada',
            name='numero_vaga',
        ),
        migrations.RemoveField(
            model_name='estada',
            name='status_vaga',
        ),
        migrations.AddField(
            model_name='estada',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaga.vaga'),
        ),
    ]
