# Generated by Django 5.2.6 on 2025-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estada', '0002_remove_estada_numero_vaga_remove_estada_status_vaga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estada',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
