# Generated by Django 5.2.6 on 2025-10-16 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estada', '0003_estada_pago'),
        ('funcionarios', '0001_initial'),
        ('vaga', '0003_configuracaovaga'),
        ('veiculo', '0002_veiculo_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modalidade_pagamento', models.CharField(max_length=10)),
                ('tempo_total', models.DurationField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaga.vaga')),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculo.veiculo')),
            ],
        ),
    ]
