# Generated by Django 5.2.6 on 2025-10-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estada', '0004_pagamentolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estada',
            name='data_entrada',
            field=models.DateTimeField(),
        ),
    ]
