# Generated by Django 5.2.6 on 2025-11-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculo', '0003_alter_veiculo_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='clientes.cliente'),
        ),
    ]
